name: Feature Request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? Let's hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What's the pain point this would solve?
      placeholder: "I keep having to manually..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think it should work?
      placeholder: "It would be nice if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Charon would this affect?
      options:
        - Frontend (UI, visualization)
        - Backend (API, analysis)
        - Both
        - New component
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, examples, links — anything that helps explain the idea.
    validations:
      required: false
